### ISSUE TITLE
Use new_checked by default

### ISSUE THREAD

**Issue by dlrobertson** [smoltcp-rs/smoltcp#195]
Currently all `Packet` types have at least the two constructor methods `new` and `new_checked`. `new` does no length checks, while `new_checked` obviously does. AFAIK in `std` etc typically the "safe" version is the default and the "unsafe" version is explicitly called with `<name>_unchecked`. Would it make sense to do something like the following?

 1) deprecate `Packet::new_checked`
 2) make `Packet::new` functions do what `Packet::new_checked` does
 3) add `Packet::new_unchecked` functions that do what `Packet::new` does

**Comment by dlrobertson** [comment]
Just a question/thought

**Comment by whitequark** [comment]
There is nothing inherently safer about constructing packets with `new_checked` because you can still get panics if you modify a length field inside the packet and then use an accessor.

Moreover, it's not even that one should be preferred over the other. In a typical network stack that both sends and receives packets there would be approximately as many calls to `new` as to `new_checked`.

I'm open to other suggestions for these names, but I think that safety is the wrong angle here.
