### ISSUE TITLE
artiq-zynq performance regression with 0.7.0

### ISSUE THREAD

**Issue by sbourdeauducq** [smoltcp-rs/smoltcp#415]
See https://git.m-labs.hk/M-Labs/artiq-zynq/issues/127

**Comment by Dirbaio** [comment]
Interesting. 
Is "H" a Linux machine and "D" a smoltcp device? Assuming so:

- H2D could be due to Delayed ACK if the rx buffer in the device is small. Can you try disabling it? 
- D2H could be due to #387 (but unlikely because the rx buffer in the Linux side is probably huge), or maybe #406 if the link is lossy (the RTT estimation will probably detect a higher RTO, the previous hardcoded RTO of 100ms was very agressive?). 

Could you provide packet captures of before and after? It would help significantly in figuring it out

**Comment by astro** [comment]
Regression occurs since the merge of #404.

**Comment by dnadlinger** [comment]
@Dirbaio: Just to confirm your interpretation, H would indeed have been a Linux box ("host") running the kernel TCP stack, and D the embedded ARM device running smoltcp.

**Comment by Dirbaio** [comment]
> Regression occurs since the merge of #404.

Okay, makes sense. 

- How is the workload like? Is it one big transfer in one direction, or many small transfers in request/response fashion? What's the TCP buffer sizes, what's the size of the writes?
- Can you provide packet capture?
- Have you tried disabling delayed ACK? `socket.set_ack_delay(None)`

**Comment by dnadlinger** [comment]
(@astro/… can hopefully provide details, as I'm only peripherally involved with this.)

**Comment by astro** [comment]
The workload sizes are 1MB, and 1KB, echoed in a request/response fashion. TCP buffer sizes are 64KB.

`socket.set_ack_delay(None)` mitigated the regression for us. A performance regression in the default settings is still worth investigating, so don't close this issue yet.

**Comment by astro** [comment]
I've done some loopback tests with delay and `FaultInjector` in an std environment but was not yet able to reproduce throughput differences between running with and without delayed acks.

**Comment by Dirbaio** [comment]
It's expected ACK delay causes issues depending on the workload (usually chatty request/response workloads). There's no default settings that will suit everyone, so it's expected people will have to tune them. Also, Linux defaults to ack_delay on FWIW.

If you believe your workload shouldn't be impacted by ack_delay but still get a performance regression, please open a new issue *with logs and packet capture*.
