### ISSUE TITLE
Can we build `IP over Serial` by the project?

### ISSUE THREAD

**Issue by rise0chen** [smoltcp-rs/smoltcp#417]
![image](https://user-images.githubusercontent.com/12853908/106707068-9129e180-662b-11eb-8d95-3cc54a283d5e.png)
It's amazing if we can realize this idea.

**Comment by Dirbaio** [comment]
This is definitely possible :)

What particular "IP over Serial" protocol are you looking for? Most common are PPP or SLIP. They transmit IP packets instead of Ethernet frames, so you will need #401 . For PPP you can use [this](https://github.com/akiles/ppproto) (beware, it's a bit WIP). SLIP is really simple, I'm sure there are some crates around.

If you don't care about compatibility with a particular protocol and want to use a released version of smoltcp (instead of #401 ) you can also send Ethernet frames over serial (with SLIP, COBS or other framing of your choice).

**Comment by rise0chen** [comment]
Both PPP and SLIP need replace `end char` by two other char, so it will need too much cost.
Maybe need another data link layer standard.

**Comment by rise0chen** [comment]
Maybe can send Ethernet frames ,and split two frames by some idle time.

**Comment by pothos** [comment]
Or parse the Ethernet header to get its length, assuming L2 headers are trusted.

**Comment by Dirbaio** [comment]
Hello! As part of issue cleanup I'm closing inactive or already-answered "question" issues, since they're not actionable.

Note this doesn't mean questions aren't welcome. They still are! It's just that they shouldn't stay open forever.
