### ISSUE TITLE
Examples are out of date

### ISSUE THREAD

**Issue by Qubasa** [smoltcp-rs/smoltcp#471]
The examples  linked in the Readme are out of date and do not compile anymore with recent versions of smoltcp. Or at least the baremetal example https://github.com/smoltcp-rs/smoltcp/blob/master/examples/loopback.rs

**Comment by Dirbaio** [comment]
The examples from latest master build with smoltcp from latest master, which has had breaking changes since the 0.7 release.

If you want to build the examples with a released smoltcp version, get them from the corresponding tag, not from master: https://github.com/smoltcp-rs/smoltcp/tree/v0.7.1/examples

**Comment by Qubasa** [comment]
Ah thanks!
