### ISSUE TITLE
Non panic version of `SocketSet::get`?

### ISSUE THREAD

**Issue by JakkuSakura** [smoltcp-rs/smoltcp#501]
It seems that there are only `SocketSet::get` that panics. Would a PR of `SocketSet::try_get` be welcome? 

I was trying to work around this by checking socket's refcount. But there is no way, neither can I tell if a socket is dropped in `prune()` or `release()`. There seems no way of detecting if a Socket is in the SocketSet, other than explicitly `iter().find()`. However, iter().find() requires another iteration.

**Comment by therealprof** [comment]
I think panics are always bad and reserved exclusively for "no good way to deal with this situation". If a fallible version is possible, we should have it.

**Comment by Dirbaio** [comment]
The issue is the Handle is just the index in the array, so it might get reused. If you're doing `get` without knowing whether the socket has been deleted or not, it might be the case that it's been deleted and *another* socket has been added in its place, so you get a completely different socket instead of a "this socket has been deleted" error.

**Comment by JakkuSakura** [comment]
Can we have `struct Handle { id: u32, index: u32 }`? We only use `index` for indexing, and use `id` for equality?

**Comment by Dirbaio** [comment]
That would incur in some extra overhead for embedded usecases. In these you usually have a static set of 1-2 sockets that stay alive forevre instead of dynamically adding/removing them. 

You can easily do your own `MySocket` wrapper type that ensures its handle is alive. Have it own a Handle, call `retain` on clone, call `release` on drop. Never call `remove`. This way you're guaranteed that if a `MySocket` instance exists, its handle is valid.

**Comment by Dirbaio** [comment]
Closing as wontfix: it's the responsibility of caller code to only use handles while they're valid. Wrong handle use may panic or may return another socket that has since then occupied the same slot.
