### ISSUE TITLE
Removal of updating neighbour cache from random packets breaks cross subnet routing for device with default routes

### ISSUE THREAD

**Issue by mbirtwell** [smoltcp-rs/smoltcp#639]
For devices which don't make any out going requests it's tempting to not bother configuring a default route and rely on smoltcp remembering where a packet came from in order to send the response to the same place. This [commit](https://github.com/smoltcp-rs/smoltcp/pull/544/commits/6210612be047ee706ac729015cdbc2581e6ae9a3) removed the code that made this work. I understand that this might not be what this was intended to achieve, but it is quite useful. 

I was wondering how you would feel about reinstating that code with some additional checks to avoid the problems that it encountered. e.g. we could only update the neighbour cache if the packet is destined for us. I'd be happy to prepare a PR.

Further background and original report: https://github.com/m-labs/artiq/issues/1930

**Comment by Dirbaio** [comment]
The fact this worked before is an accident, the fix is to set the correct IP configuration on devices, not to add back opportunistic ARP cache population. Commented on https://github.com/m-labs/artiq/issues/1930 with details.

It's still likely we want some restricted form of cache population back, but due to performance reasons (#597). Since this is already tracked in #597, I'm going to close this.

**Comment by adamgreig** [comment]
I think the potential change discussed in #597 (add incoming MACs to neighbour cache only if src+dst ip+mac are unicast and dst ip+mac are ours) would probably be enough to restore the (dubious) functionality artiq is relying on, since packets from the router would pass this filter and be included in the cache.

I still think it's a reasonable policy for adding to the neighbour cache, but it would be good to find out what Linux does exactly. It seems super cursed that this means one could set netmask to 0 and rely on the neighbour cache having an entry with the router's MAC and each foreign IP instead of configuring a gateway (if nothing else performance would quickly become _terrible_ as the cache fills up) so maybe making that impossible is a reason to keep the stricter cache policy...
