### ISSUE TITLE
Panic when solving URI with mDNS

### ISSUE THREAD

**Issue by ODCA117** [smoltcp-rs/smoltcp#941]
I tried to enable the following feature in embassy-net #[cfg(feature = "socket-mdns")] to be able to resolve this URI _homeassistant.local_ in rp pico. I was able to enable mdns feature but when trying to resolve the URI smoltcp panics with 
```
smoltcp-0.11.0/src/iface/interface/mod.rs:882:14:
called `Option::unwrap()` on a `None` value
```

**Comment by Dirbaio** [comment]
panic is here https://github.com/smoltcp-rs/smoltcp/blob/v0.11.0/src/iface/interface/mod.rs#L882

it happens because you haven't configured any ipv6 address in the interface. Are you actually intending to use IPv6? if no, disable it. if yes, configure an address.

(we should probably look into preventing mDNS from trying to use ipv6 if you have no ipv6 addr, or at least not panic...)

**Comment by aurelj** [comment]
Note that the panic seems to already be fixed in the current git tree.

You can try the git version adding this in your `Cargo.toml`:
```toml
[patch.crates-io]
smoltcp = { git = "https://github.com/smoltcp-rs/smoltcp.git" }
```

**Comment by thvdveld** [comment]
The panic is still there, but in a different place: https://github.com/smoltcp-rs/smoltcp/blob/80257520132e18caa59d20fa200917a01c67e68d/src/socket/dns.rs#L615

There is a panic when there is no IPv4 or IPv6 address configured when sending to an IPv4 or IPv6 address respectively. We should handle this case differently.
